### ISSUE TITLE
[Bug] No damage indicators

### ISSUE THREAD

**Issue by Khrystyian** [Beelzebu/DamageIndicator#10]
Hello! 

I'm having some issues with DamageIndicator, to be short, it doesn't show the damage indicator on Spigot 1.16.4.

The problem is that the damage indicators do not show when players hit mobs, only when take damage from the world (e. g fire, fall damage, etc)

Config.yml
https://pastebin.com/FREemTqC

**Comment by jsuarezl** [comment]
Error was fixed on [version 1.3.8](https://www.spigotmc.org/resources/55974/update?update=433314).
