### ISSUE TITLE
particles show but no holo for damage/health

### ISSUE THREAD

**Issue by phat-male** [Beelzebu/DamageIndicator#8]
The blood particles display though I am unable to get the damage or healing holograms on default settings. I also have holographic displays installed incase it needed a holographic plugin too.
How can I get the holograms to display as I would love to use this plugin
also I'm on latest 1.16.4 version of Minecraft.

DamageIndicator v1.3.7
HolographicDisplays v2.4.5

**Comment by jsuarezl** [comment]
Error was fixed on [version 1.3.8](https://www.spigotmc.org/resources/55974/update?update=433314).
